export const seedData = {
  clients: [
    {
      id: 'client-1',
      name: 'Sarah Mitchell',
      initials: 'SM',
      tier: 2,
      address: '8420 E Camelback Rd, Paradise Valley, AZ 85253',
      retainer: 6000,
      since: '2026-01-15',
      nextVisit: '2026-04-18',
      lastVisit: '2026-04-04',
      phone: '(480) 555-0142',
      email: 'sarah@mitchellventures.com',
      status: 'Active',
      preferences: {
        property: {
          arrivalTemp: '72°F',
          poolTemp: '84°F',
          lighting: 'Warm, dimmed on arrival',
          guestRoomSetup: 'Fresh linens, flowers in vase',
          alarmCode: '4291*',
          gateCode: '#7823',
          parking: 'Tesla in garage, guest car in driveway',
        },
        grocery: {
          staples: 'Almond milk, kombucha, Siete chips, fresh flowers weekly',
          dietary: 'Gluten-free, no dairy',
          brands: 'Whole Foods preferred, Sprouts acceptable',
          beverages: 'Whispering Angel rosé, LaCroix, Liquid IV',
          wine: 'Whispering Angel, Kim Crawford Sauvignon Blanc',
        },
        lifestyle: {
          restaurants: 'Mastros, Bourbon Steak, Nobu, Hearth 61',
          travelStyle: 'Private aviation preferred, Wheels Up member',
          vehiclePreferences: 'Tesla Model S in residence, Escalade for airport runs',
          activities: 'Pilates, hiking Camelback, golf at Desert Mountain',
          events: 'Barrett-Jackson, Waste Management Open',
        },
        communication: {
          preferredChannel: 'Text',
          preferredTiming: 'After 9am, before 8pm',
          detailLevel: 'Summary only, no lengthy updates',
        },
        importantDates: {
          birthday: 'March 14',
          anniversary: 'June 22',
          regularArrival: 'Every 3–4 weeks',
          special: 'Wine tasting trip planned for September',
        },
      },
      property: {
        sqft: 5800,
        bedrooms: 5,
        bathrooms: 4,
        pool: true,
        yearBuilt: 2019,
        systems: {
          hvac:       { model: 'Carrier Infinity 26', lastService: '2026-02-20', status: 'Good' },
          pool:       { equipment: 'Pentair Variable Speed', lastService: '2026-04-01', status: 'Good' },
          security:   { system: 'Alarm.com with cameras', status: 'Active' },
          irrigation: { system: 'Hunter Pro-C', lastService: '2026-03-15', status: 'Scheduled' },
          landscaping:{ vendor: 'Verde Landscaping', lastService: '2026-04-04', status: 'Good' },
        },
        inspections: [
          { id: 'i1-1', date: '2026-04-04', summary: 'All systems normal', issues: 0, notes: 'Pool at 84°F. HVAC filters clean. Landscaping trimmed. Interior clean and ready.' },
          { id: 'i1-2', date: '2026-03-20', summary: '1 item noted', issues: 1, notes: 'Irrigation timer needed adjustment on east zone. Corrected on-site.' },
          { id: 'i1-3', date: '2026-03-06', summary: 'All systems normal', issues: 0, notes: 'Pest control completed. Pool serviced. All clear.' },
          { id: 'i1-4', date: '2026-02-21', summary: 'All systems normal', issues: 0, notes: 'Pre-arrival prep completed. Groceries stocked. Guest room set.' },
          { id: 'i1-5', date: '2026-02-07', summary: '2 items noted', issues: 2, notes: 'HVAC filter due for replacement — completed. Minor crack in pool coping — sealed.' },
        ],
      },
      notes: [
        { id: 'n1-1', date: '2026-04-09', type: 'call', content: 'Sarah called to request Mastros reservation for Saturday. Party of 4. Waiting on confirmation of time.' },
        { id: 'n1-2', date: '2026-04-04', type: 'visit', content: 'Completed full property walkthrough. Pool at 84°F. Stocked groceries per preference profile. Property immaculate.' },
        { id: 'n1-3', date: '2026-03-22', type: 'text', content: 'Texted Sarah arrival prep confirmation. She responded with thumbs up and noted she\'ll arrive ~6pm Friday.' },
      ],
      billing: {
        paymentStatus: 'Paid',
        alaCarte: [
          { id: 'b1-1', description: 'Grocery run — Whispering Angel + arrival staples', amount: 287 },
          { id: 'b1-2', description: 'Escalade airport transfer coordination', amount: 150 },
        ],
        history: [
          { month: 'Nov 2025', retainer: 6000, extras: 0,   total: 6000,  status: 'Paid' },
          { month: 'Dec 2025', retainer: 6000, extras: 450, total: 6450,  status: 'Paid' },
          { month: 'Jan 2026', retainer: 6000, extras: 287, total: 6287,  status: 'Paid' },
          { month: 'Feb 2026', retainer: 6000, extras: 620, total: 6620,  status: 'Paid' },
          { month: 'Mar 2026', retainer: 6000, extras: 350, total: 6350,  status: 'Paid' },
          { month: 'Apr 2026', retainer: 6000, extras: 437, total: 6437,  status: 'Pending' },
        ],
      },
    },
    {
      id: 'client-2',
      name: 'James Worthington',
      initials: 'JW',
      tier: 1,
      address: '15200 N Scottsdale Rd, Scottsdale, AZ 85254',
      retainer: 1000,
      since: '2026-02-01',
      nextVisit: '2026-04-22',
      lastVisit: '2026-03-28',
      phone: '(602) 555-0198',
      email: 'jworthington@worthcap.com',
      status: 'Active',
      preferences: {
        property: {
          arrivalTemp: '70°F',
          poolTemp: '82°F',
          lighting: 'Full brightness on arrival',
          guestRoomSetup: 'Standard setup',
          alarmCode: '8834*',
          gateCode: '#1156',
          parking: 'F-150 in garage',
        },
        grocery: {
          staples: 'Sparkling water, IPA beer, ribeye steaks, coffee pods',
          dietary: 'No restrictions',
          brands: "Whole Foods, AJ's Fine Foods",
          beverages: 'Modelo, Liquid Death water, Bulletproof coffee',
          wine: 'Caymus Cabernet, Jordan Chardonnay',
        },
        lifestyle: {
          restaurants: 'Maple & Ash, Steak 44, El Chorro',
          travelStyle: 'Commercial first class, TSA PreCheck',
          vehiclePreferences: 'F-150 Platinum in residence',
          activities: 'Golf, Diamondbacks games, college football',
          events: 'Cardinals games, Phoenix Open',
        },
        communication: {
          preferredChannel: 'Email',
          preferredTiming: 'Mornings before 10am',
          detailLevel: 'Full detail with photos',
        },
        importantDates: {
          birthday: 'November 8',
          anniversary: 'August 15',
          regularArrival: 'Monthly, first weekend',
          special: 'Super Bowl week in February annually',
        },
      },
      property: {
        sqft: 3200,
        bedrooms: 4,
        bathrooms: 3,
        pool: true,
        yearBuilt: 2015,
        systems: {
          hvac:       { model: 'Trane XV21i', lastService: '2026-01-15', status: 'Good' },
          pool:       { equipment: 'Hayward Variable Speed', lastService: '2026-03-20', status: 'Good' },
          security:   { system: 'Ring Alarm Pro', status: 'Active' },
          irrigation: { system: 'Rachio 3', lastService: '2026-02-10', status: 'Good' },
          landscaping:{ vendor: 'Verde Landscaping', lastService: '2026-03-28', status: 'Good' },
        },
        inspections: [
          { id: 'i2-1', date: '2026-03-28', summary: 'All systems normal', issues: 0, notes: 'Landscaping completed. Pool clean. All systems nominal.' },
          { id: 'i2-2', date: '2026-03-07', summary: '1 item noted', issues: 1, notes: 'Broken irrigation head on east lawn — replaced. All other systems good.' },
          { id: 'i2-3', date: '2026-02-14', summary: 'All systems normal', issues: 0, notes: 'Super Bowl week prep completed. Groceries, coolers, and setup done.' },
        ],
      },
      notes: [
        { id: 'n2-1', date: '2026-04-08', type: 'email', content: 'Emailed James the April visit summary with photos. He replied confirming he\'ll arrive April 22 with his son for a golf trip.' },
        { id: 'n2-2', date: '2026-03-28', type: 'visit', content: 'Full property inspection completed. No issues. Landscaping team was on-site for quarterly trim.' },
      ],
      billing: {
        paymentStatus: 'Paid',
        alaCarte: [
          { id: 'b2-1', description: 'HVAC filter replacement (MERV-13, 4 units)', amount: 85 },
        ],
        history: [
          { month: 'Feb 2026', retainer: 1000, extras: 0,  total: 1000, status: 'Paid' },
          { month: 'Mar 2026', retainer: 1000, extras: 85, total: 1085, status: 'Paid' },
          { month: 'Apr 2026', retainer: 1000, extras: 85, total: 1085, status: 'Pending' },
        ],
      },
    },
  ],

  tasks: [
    {
      id: 'task-1',
      clientId: 'client-1',
      clientName: 'Sarah Mitchell',
      title: 'Pre-arrival pool heating to 84°F',
      category: 'Estate Management',
      status: 'In Progress',
      priority: 'High',
      dueDate: '2026-04-17',
      notes: 'Start pool heating 24hrs before arrival on the 18th. Confirm with Azure Pool Service.',
      createdAt: '2026-04-10',
    },
    {
      id: 'task-2',
      clientId: 'client-1',
      clientName: 'Sarah Mitchell',
      title: 'Grocery run — Whispering Angel + arrival staples',
      category: 'Lifestyle & Acquisitions',
      status: 'New',
      priority: 'High',
      dueDate: '2026-04-17',
      notes: 'Standard arrival groceries per preference profile. 2 bottles Whispering Angel rosé, LaCroix, almond milk, Siete chips, flowers.',
      createdAt: '2026-04-11',
    },
    {
      id: 'task-3',
      clientId: 'client-1',
      clientName: 'Sarah Mitchell',
      title: 'Coordinate Mastros dinner reservation — Sat 7:30pm',
      category: 'Lifestyle & Acquisitions',
      status: 'Awaiting Client',
      priority: 'Medium',
      dueDate: '2026-04-19',
      notes: "Client requested Saturday 7:30pm. Waiting on confirmation of party size from Sarah.",
      createdAt: '2026-04-09',
    },
    {
      id: 'task-4',
      clientId: 'client-2',
      clientName: 'James Worthington',
      title: 'HVAC filter replacement (all 4 units)',
      category: 'Estate Management',
      status: 'New',
      priority: 'Medium',
      dueDate: '2026-04-20',
      notes: '3-month replacement cycle due. Use MERV-13 filters x4. Desert Cool HVAC on-call.',
      createdAt: '2026-04-08',
    },
    {
      id: 'task-5',
      clientId: 'client-2',
      clientName: 'James Worthington',
      title: 'April arrival prep — golf trip',
      category: 'Estate Management',
      status: 'New',
      priority: 'High',
      dueDate: '2026-04-21',
      notes: 'James arrives April 22 with son for golf trip. Stock fridge: Modelo, ribeyes, Caymus cab. Pull golf cart out of storage.',
      createdAt: '2026-04-11',
    },
    {
      id: 'task-6',
      clientId: 'client-2',
      clientName: 'James Worthington',
      title: 'Landscaping quarterly inspection',
      category: 'Estate Management',
      status: 'Completed',
      priority: 'Low',
      dueDate: '2026-04-05',
      notes: 'All irrigation heads checked. One broken head replaced on east side. Verde Landscaping on-site.',
      createdAt: '2026-04-01',
      completedAt: '2026-04-05',
    },
  ],

  vendors: [
    { id: 'v1', name: 'Desert Cool HVAC', category: 'HVAC', phone: '(480) 555-0210', email: 'service@desertcoolaz.com', rating: 5, notes: 'Preferred HVAC contractor. Same-day response. Carrier certified.', lastUsed: '2026-02-20', status: 'Active' },
    { id: 'v2', name: 'Azure Pool Service', category: 'Pool', phone: '(480) 555-0334', email: 'azure@azurepoolsaz.com', rating: 5, notes: 'Weekly service for both clients. Excellent. Pentair & Hayward certified.', lastUsed: '2026-04-01', status: 'Active' },
    { id: 'v3', name: 'Verde Landscaping', category: 'Landscaping', phone: '(602) 555-0456', email: 'info@verdelandscapingaz.com', rating: 4, notes: 'Bi-weekly service. Good work but slow on project quotes. Reliable for routine maintenance.', lastUsed: '2026-04-05', status: 'Active' },
    { id: 'v4', name: 'Sonoran Clean', category: 'Cleaning', phone: '(480) 555-0567', email: 'clean@sonoranclean.com', rating: 5, notes: 'Trusted cleaning crew. Always on time. Background-checked staff. Have house keys.', lastUsed: '2026-04-10', status: 'Active' },
    { id: 'v5', name: 'PV Pest Control', category: 'Pest', phone: '(480) 555-0678', email: 'pv@pvpestaz.com', rating: 4, notes: 'Quarterly service. Effective for scorpion/spider treatment. Licensed & insured.', lastUsed: '2026-03-01', status: 'Active' },
    { id: 'v6', name: 'Fix It Right Handyman', category: 'Handyman', phone: '(602) 555-0789', email: 'fixitright@gmail.com', rating: 3, notes: 'OK for small jobs. Slow on complex work. Use only when primary contractors are unavailable.', lastUsed: '2026-02-15', status: 'Backup' },
    { id: 'v7', name: 'Ironwood Security', category: 'Security', phone: '(480) 555-0890', email: 'support@ironwoodsecurityaz.com', rating: 5, notes: 'System monitoring, installation and response. Alarm.com certified partner.', lastUsed: '2026-01-10', status: 'Active' },
    { id: 'v8', name: 'Whole Foods Scottsdale', category: 'Grocery', phone: '(480) 555-0901', email: 'delivery@wholefoods.com', rating: 5, notes: 'Preferred for grocery orders. Amazon Prime delivery. Loyalty account under Avara Home account.', lastUsed: '2026-04-10', status: 'Active' },
  ],

  outreach: [
    { id: 'o1', name: 'Walt Danley', company: 'Walt Danley Scottsdale', phone: '480-991-2050', email: 'walt@waltdanley.com', type: 'Realtor', priority: 'Hot', lastContact: '2026-03-28', nextFollowup: '2026-04-15', status: 'In Progress', notes: 'Met at PV Arts fundraiser. Very interested in referring second-home clients. Has 3 active closings in PV.' },
    { id: 'o2', name: 'Katrina Barrett', company: 'Local Luxury RE', phone: '', email: 'katrina@localluxuryre.com', type: 'Realtor', priority: 'Hot', lastContact: '2026-04-01', nextFollowup: '2026-04-20', status: 'In Progress', notes: 'Cold outreach via email. Positive response. Meeting to be scheduled.' },
    { id: 'o3', name: 'Silje Norbye Garner', company: 'BedBrock RE', phone: '602-617-0320', email: 'realestate@bedbrock.com', type: 'Realtor', priority: 'Hot', lastContact: '2026-03-15', nextFollowup: '2026-04-18', status: 'In Progress', notes: 'Connected to BedBrock Developers. Dual referral potential (buyer + builder). Follow up on new Arcadia listings.' },
    { id: 'o4', name: 'The Lucky Team', company: "Russ Lyon Sotheby's", phone: '602-320-8415', email: 'all.lucky@russlyon.com', type: 'Realtor', priority: 'Hot', lastContact: '2026-04-05', nextFollowup: '2026-04-25', status: 'In Progress', notes: 'Top producing team in PV. Referral partnership discussed. They want co-branded materials.' },
    { id: 'o5', name: 'Frank DiMaggio', company: 'AZ Homes', phone: '', email: 'info@azhomes.com', type: 'Realtor', priority: 'Warm', lastContact: '2026-03-01', nextFollowup: '2026-04-30', status: 'Cold', notes: 'No response to initial outreach. Try again with updated materials.' },
    { id: 'o6', name: 'Tony Calvis', company: 'Calvis Wyant Luxury Homes', phone: '480-905-0200', email: 'tony@calviswyant.com', type: 'Builder', priority: 'Hot', lastContact: '2026-04-08', nextFollowup: '2026-04-22', status: 'In Progress', notes: 'Custom luxury builder. Many second-home clients. Interested in adding Avara to their new-owner welcome package.' },
    { id: 'o7', name: 'Rich Brock', company: 'BedBrock Developers', phone: '602-617-0320', email: 'realestate@bedbrock.com', type: 'Builder', priority: 'Hot', lastContact: '2026-03-20', nextFollowup: '2026-04-18', status: 'In Progress', notes: 'Building several PV estates. Strong partnership potential. Silje connection helps.' },
    { id: 'o8', name: 'Mark Hancock', company: 'Camelot Homes', phone: '(480) 367-4300', email: '', type: 'Builder', priority: 'Warm', lastContact: '2026-02-15', nextFollowup: '2026-05-01', status: 'Cold', notes: 'Large volume builder. Lower-luxury tier but high referral volume. Consider a tiered pitch.' },
    { id: 'o9', name: 'Sam Fratantoni', company: 'Fratantoni Luxury Estates', phone: '', email: 'info@fratantoniluxuryestates.com', type: 'Builder', priority: 'Warm', lastContact: '2026-03-10', nextFollowup: '2026-04-28', status: 'In Progress', notes: 'Ultra-high-end custom builds ($5M+). Perfect profile match. CEO meeting requested.' },
    { id: 'o10', name: 'Rafterhouse', company: 'Rafterhouse Design + Build', phone: '(contact via website)', email: '', type: 'Builder', priority: 'Cold', lastContact: '2026-02-01', nextFollowup: '2026-06-01', status: 'Cold', notes: 'Modern aesthetic, younger demographic. Lower overlap with target client profile. Low priority.' },
  ],

  prospects: [
    { id: 'p1', name: 'Robert & Helen Crane', source: 'Realtor Ref', referredBy: 'Walt Danley', potentialTier: 2, status: 'Meeting Scheduled', addedDate: '2026-03-30', notes: 'PV estate, snowbird couple from Chicago. 2 properties. Very interested.', meetingDate: '2026-04-16' },
    { id: 'p2', name: 'Dr. Michael Ortiz', source: 'Builder Ref', referredBy: 'Tony Calvis', potentialTier: 1, status: 'Contacted', addedDate: '2026-04-05', notes: 'New Calvis Wyant build completing Q3 2026. Moving from LA.', meetingDate: null },
    { id: 'p3', name: 'Chen Family Trust', source: 'Ads', referredBy: null, potentialTier: 2, status: 'Proposal Sent', addedDate: '2026-04-02', notes: '3 investment properties in Scottsdale. Looking for full-portfolio management.', meetingDate: null },
    { id: 'p4', name: 'Katharine Ellison', source: 'Event', referredBy: null, potentialTier: 1, status: 'Contacted', addedDate: '2026-04-08', notes: 'Met at Desert Mountain Golf Club member event. Has PV vacation home she visits 6x/year.', meetingDate: null },
  ],

  activity: [
    { id: 'act-1', type: 'task_completed', content: "Landscaping quarterly inspection completed — James Worthington's property", clientName: 'James Worthington', timestamp: '2026-04-05T14:30:00' },
    { id: 'act-2', type: 'visit_logged', content: "Property visit completed — 8420 E Camelback Rd", clientName: 'Sarah Mitchell', timestamp: '2026-04-04T11:00:00' },
    { id: 'act-3', type: 'request_received', content: "New request: Coordinate Mastros dinner reservation", clientName: 'Sarah Mitchell', timestamp: '2026-04-09T15:20:00' },
    { id: 'act-4', type: 'note_added', content: "Note added: April golf trip arrival confirmed for the 22nd", clientName: 'James Worthington', timestamp: '2026-04-08T09:10:00' },
    { id: 'act-5', type: 'task_completed', content: "Smart lock battery replacement completed", clientName: 'James Worthington', timestamp: '2026-04-01T13:45:00' },
    { id: 'act-6', type: 'vendor_contacted', content: "Azure Pool Service scheduled for Sarah Mitchell pre-arrival pool heat", clientName: 'Sarah Mitchell', timestamp: '2026-04-10T08:00:00' },
    { id: 'act-7', type: 'prospect_added', content: "New prospect added: Robert & Helen Crane (via Walt Danley)", clientName: null, timestamp: '2026-03-30T16:00:00' },
    { id: 'act-8', type: 'visit_logged', content: "Property visit completed — 15200 N Scottsdale Rd", clientName: 'James Worthington', timestamp: '2026-03-28T10:30:00' },
    { id: 'act-9', type: 'request_received', content: "New task created: HVAC filter replacement", clientName: 'James Worthington', timestamp: '2026-04-08T08:00:00' },
    { id: 'act-10', type: 'note_added', content: "Note added: Grocery run and arrival prep details confirmed", clientName: 'Sarah Mitchell', timestamp: '2026-03-22T09:00:00' },
  ],

  messages: {
    'client-1': [
      { id: 'msg-1-1', sender: 'avara', content: 'Good morning, Sarah. Your property is looking beautiful. Pool is at 84°F and everything is set for your arrival Friday.', timestamp: '2026-04-11T09:00:00' },
      { id: 'msg-1-2', sender: 'client', content: "Perfect! Can you also make sure the guest room is fully set up? We're bringing friends this trip.", timestamp: '2026-04-11T09:18:00' },
      { id: 'msg-1-3', sender: 'avara', content: "Absolutely — guest room will be fully prepped with fresh linens and a floral arrangement. Anything specific you'd like in there?", timestamp: '2026-04-11T09:25:00' },
      { id: 'msg-1-4', sender: 'client', content: 'Maybe a little welcome basket? Sparkling water and some chocolates. And can you book Mastros for Saturday night?', timestamp: '2026-04-11T09:40:00' },
      { id: 'msg-1-5', sender: 'avara', content: "Done. Welcome basket is on the list. For Mastros — preferred time Saturday and how many in the party?", timestamp: '2026-04-11T09:45:00' },
    ],
    'client-2': [
      { id: 'msg-2-1', sender: 'avara', content: "Good morning, James. Just confirming your April 22nd arrival. We'll have the property ready — fridge stocked, golf cart pulled out. Anything else you need?", timestamp: '2026-04-08T08:30:00' },
      { id: 'msg-2-2', sender: 'client', content: "Sounds good. Make sure there's Modelo and the Caymus in the wine fridge. Arriving around 4pm.", timestamp: '2026-04-08T10:15:00' },
      { id: 'msg-2-3', sender: 'avara', content: "All noted. Modelo in the fridge, Caymus in the wine cooler, golf cart ready in the garage. We'll also have the HVAC filters replaced before you arrive.", timestamp: '2026-04-08T10:22:00' },
    ],
  },
}
